<?php
/**
 * ImageFormat
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TemplateFox\Model;
use \TemplateFox\ObjectSerializer;

/**
 * ImageFormat Class Doc Comment
 *
 * @category Class
 * @description Image output format options
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ImageFormat
{
    /**
     * Possible values of this enum
     */
    public const PNG = 'png';

    public const JPEG = 'jpeg';

    public const WEBP = 'webp';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PNG,
            self::JPEG,
            self::WEBP
        ];
    }
}


