<?php
/**
 * MergePdfRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TemplateFox\Model;

use \ArrayAccess;
use \TemplateFox\ObjectSerializer;

/**
 * MergePdfRequest Class Doc Comment
 *
 * @category Class
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MergePdfRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MergePdfRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'export_type' => '\TemplateFox\Model\AppRoutersV1PdfToolsExportType',
        'expiration' => 'int',
        'filename' => 'string',
        'pdfs' => '\TemplateFox\Model\PdfInput[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'export_type' => null,
        'expiration' => null,
        'filename' => null,
        'pdfs' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'export_type' => false,
        'expiration' => false,
        'filename' => true,
        'pdfs' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'export_type' => 'export_type',
        'expiration' => 'expiration',
        'filename' => 'filename',
        'pdfs' => 'pdfs'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'export_type' => 'setExportType',
        'expiration' => 'setExpiration',
        'filename' => 'setFilename',
        'pdfs' => 'setPdfs'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'export_type' => 'getExportType',
        'expiration' => 'getExpiration',
        'filename' => 'getFilename',
        'pdfs' => 'getPdfs'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('export_type', $data ?? [], null);
        $this->setIfExists('expiration', $data ?? [], 86400);
        $this->setIfExists('filename', $data ?? [], null);
        $this->setIfExists('pdfs', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['expiration']) && ($this->container['expiration'] > 604800)) {
            $invalidProperties[] = "invalid value for 'expiration', must be smaller than or equal to 604800.";
        }

        if (!is_null($this->container['expiration']) && ($this->container['expiration'] < 60)) {
            $invalidProperties[] = "invalid value for 'expiration', must be bigger than or equal to 60.";
        }

        if (!is_null($this->container['filename']) && (mb_strlen($this->container['filename']) > 100)) {
            $invalidProperties[] = "invalid value for 'filename', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['filename']) && !preg_match("/^[a-zA-Z0-9_\\-\\.]+$/", $this->container['filename'])) {
            $invalidProperties[] = "invalid value for 'filename', must be conform to the pattern /^[a-zA-Z0-9_\\-\\.]+$/.";
        }

        if ($this->container['pdfs'] === null) {
            $invalidProperties[] = "'pdfs' can't be null";
        }
        if ((count($this->container['pdfs']) < 2)) {
            $invalidProperties[] = "invalid value for 'pdfs', number of items must be greater than or equal to 2.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets export_type
     *
     * @return \TemplateFox\Model\AppRoutersV1PdfToolsExportType|null
     */
    public function getExportType()
    {
        return $this->container['export_type'];
    }

    /**
     * Sets export_type
     *
     * @param \TemplateFox\Model\AppRoutersV1PdfToolsExportType|null $export_type `url` uploads to CDN and returns URL, `binary` returns raw PDF bytes
     *
     * @return self
     */
    public function setExportType($export_type)
    {
        if (is_null($export_type)) {
            throw new \InvalidArgumentException('non-nullable export_type cannot be null');
        }
        $this->container['export_type'] = $export_type;

        return $this;
    }

    /**
     * Gets expiration
     *
     * @return int|null
     */
    public function getExpiration()
    {
        return $this->container['expiration'];
    }

    /**
     * Sets expiration
     *
     * @param int|null $expiration URL expiration in seconds. Min 60, max 604800. Only applies to `url` export type.
     *
     * @return self
     */
    public function setExpiration($expiration)
    {
        if (is_null($expiration)) {
            throw new \InvalidArgumentException('non-nullable expiration cannot be null');
        }

        if (($expiration > 604800)) {
            throw new \InvalidArgumentException('invalid value for $expiration when calling MergePdfRequest., must be smaller than or equal to 604800.');
        }
        if (($expiration < 60)) {
            throw new \InvalidArgumentException('invalid value for $expiration when calling MergePdfRequest., must be bigger than or equal to 60.');
        }

        $this->container['expiration'] = $expiration;

        return $this;
    }

    /**
     * Gets filename
     *
     * @return string|null
     */
    public function getFilename()
    {
        return $this->container['filename'];
    }

    /**
     * Sets filename
     *
     * @param string|null $filename filename
     *
     * @return self
     */
    public function setFilename($filename)
    {
        if (is_null($filename)) {
            array_push($this->openAPINullablesSetToNull, 'filename');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('filename', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($filename) && (mb_strlen($filename) > 100)) {
            throw new \InvalidArgumentException('invalid length for $filename when calling MergePdfRequest., must be smaller than or equal to 100.');
        }
        if (!is_null($filename) && (!preg_match("/^[a-zA-Z0-9_\\-\\.]+$/", ObjectSerializer::toString($filename)))) {
            throw new \InvalidArgumentException("invalid value for \$filename when calling MergePdfRequest., must conform to the pattern /^[a-zA-Z0-9_\\-\\.]+$/.");
        }

        $this->container['filename'] = $filename;

        return $this;
    }

    /**
     * Gets pdfs
     *
     * @return \TemplateFox\Model\PdfInput[]
     */
    public function getPdfs()
    {
        return $this->container['pdfs'];
    }

    /**
     * Sets pdfs
     *
     * @param \TemplateFox\Model\PdfInput[] $pdfs Ordered list of PDFs to merge. Each entry has either `pdf_url` or `pdf_base64`. Minimum 2.
     *
     * @return self
     */
    public function setPdfs($pdfs)
    {
        if (is_null($pdfs)) {
            throw new \InvalidArgumentException('non-nullable pdfs cannot be null');
        }


        if ((count($pdfs) < 2)) {
            throw new \InvalidArgumentException('invalid length for $pdfs when calling MergePdfRequest., number of items must be greater than or equal to 2.');
        }
        $this->container['pdfs'] = $pdfs;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


