<?php
/**
 * PdfVariant
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.9.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TemplateFox\Model;
use \TemplateFox\ObjectSerializer;

/**
 * PdfVariant Class Doc Comment
 *
 * @category Class
 * @description PDF variant for standards-compliant output (PDF/A).
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PdfVariant
{
    /**
     * Possible values of this enum
     */
    public const PDF_A_1B = 'pdf/a-1b';

    public const PDF_A_2B = 'pdf/a-2b';

    public const PDF_A_3B = 'pdf/a-3b';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PDF_A_1B,
            self::PDF_A_2B,
            self::PDF_A_3B
        ];
    }
}


