<?php
/**
 * S3ConfigResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TemplateFox\Model;

use \ArrayAccess;
use \TemplateFox\ObjectSerializer;

/**
 * S3ConfigResponse Class Doc Comment
 *
 * @category Class
 * @description Response for S3 configuration (with masked secret)
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class S3ConfigResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'S3ConfigResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'configured' => 'bool',
        'endpoint_url' => 'string',
        'access_key_id' => 'string',
        'secret_access_key_masked' => 'string',
        'bucket_name' => 'string',
        'default_prefix' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'configured' => null,
        'endpoint_url' => null,
        'access_key_id' => null,
        'secret_access_key_masked' => null,
        'bucket_name' => null,
        'default_prefix' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'configured' => false,
        'endpoint_url' => false,
        'access_key_id' => false,
        'secret_access_key_masked' => false,
        'bucket_name' => false,
        'default_prefix' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'configured' => 'configured',
        'endpoint_url' => 'endpoint_url',
        'access_key_id' => 'access_key_id',
        'secret_access_key_masked' => 'secret_access_key_masked',
        'bucket_name' => 'bucket_name',
        'default_prefix' => 'default_prefix'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'configured' => 'setConfigured',
        'endpoint_url' => 'setEndpointUrl',
        'access_key_id' => 'setAccessKeyId',
        'secret_access_key_masked' => 'setSecretAccessKeyMasked',
        'bucket_name' => 'setBucketName',
        'default_prefix' => 'setDefaultPrefix'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'configured' => 'getConfigured',
        'endpoint_url' => 'getEndpointUrl',
        'access_key_id' => 'getAccessKeyId',
        'secret_access_key_masked' => 'getSecretAccessKeyMasked',
        'bucket_name' => 'getBucketName',
        'default_prefix' => 'getDefaultPrefix'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('configured', $data ?? [], null);
        $this->setIfExists('endpoint_url', $data ?? [], null);
        $this->setIfExists('access_key_id', $data ?? [], null);
        $this->setIfExists('secret_access_key_masked', $data ?? [], null);
        $this->setIfExists('bucket_name', $data ?? [], null);
        $this->setIfExists('default_prefix', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['configured'] === null) {
            $invalidProperties[] = "'configured' can't be null";
        }
        if ($this->container['endpoint_url'] === null) {
            $invalidProperties[] = "'endpoint_url' can't be null";
        }
        if ($this->container['access_key_id'] === null) {
            $invalidProperties[] = "'access_key_id' can't be null";
        }
        if ($this->container['secret_access_key_masked'] === null) {
            $invalidProperties[] = "'secret_access_key_masked' can't be null";
        }
        if ($this->container['bucket_name'] === null) {
            $invalidProperties[] = "'bucket_name' can't be null";
        }
        if ($this->container['default_prefix'] === null) {
            $invalidProperties[] = "'default_prefix' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets configured
     *
     * @return bool
     */
    public function getConfigured()
    {
        return $this->container['configured'];
    }

    /**
     * Sets configured
     *
     * @param bool $configured Whether S3 is configured
     *
     * @return self
     */
    public function setConfigured($configured)
    {
        if (is_null($configured)) {
            throw new \InvalidArgumentException('non-nullable configured cannot be null');
        }
        $this->container['configured'] = $configured;

        return $this;
    }

    /**
     * Gets endpoint_url
     *
     * @return string
     */
    public function getEndpointUrl()
    {
        return $this->container['endpoint_url'];
    }

    /**
     * Sets endpoint_url
     *
     * @param string $endpoint_url S3-compatible endpoint URL
     *
     * @return self
     */
    public function setEndpointUrl($endpoint_url)
    {
        if (is_null($endpoint_url)) {
            throw new \InvalidArgumentException('non-nullable endpoint_url cannot be null');
        }
        $this->container['endpoint_url'] = $endpoint_url;

        return $this;
    }

    /**
     * Gets access_key_id
     *
     * @return string
     */
    public function getAccessKeyId()
    {
        return $this->container['access_key_id'];
    }

    /**
     * Sets access_key_id
     *
     * @param string $access_key_id Access key ID
     *
     * @return self
     */
    public function setAccessKeyId($access_key_id)
    {
        if (is_null($access_key_id)) {
            throw new \InvalidArgumentException('non-nullable access_key_id cannot be null');
        }
        $this->container['access_key_id'] = $access_key_id;

        return $this;
    }

    /**
     * Gets secret_access_key_masked
     *
     * @return string
     */
    public function getSecretAccessKeyMasked()
    {
        return $this->container['secret_access_key_masked'];
    }

    /**
     * Sets secret_access_key_masked
     *
     * @param string $secret_access_key_masked Masked secret access key (shows first 4 and last 4 characters)
     *
     * @return self
     */
    public function setSecretAccessKeyMasked($secret_access_key_masked)
    {
        if (is_null($secret_access_key_masked)) {
            throw new \InvalidArgumentException('non-nullable secret_access_key_masked cannot be null');
        }
        $this->container['secret_access_key_masked'] = $secret_access_key_masked;

        return $this;
    }

    /**
     * Gets bucket_name
     *
     * @return string
     */
    public function getBucketName()
    {
        return $this->container['bucket_name'];
    }

    /**
     * Sets bucket_name
     *
     * @param string $bucket_name S3 bucket name
     *
     * @return self
     */
    public function setBucketName($bucket_name)
    {
        if (is_null($bucket_name)) {
            throw new \InvalidArgumentException('non-nullable bucket_name cannot be null');
        }
        $this->container['bucket_name'] = $bucket_name;

        return $this;
    }

    /**
     * Gets default_prefix
     *
     * @return string
     */
    public function getDefaultPrefix()
    {
        return $this->container['default_prefix'];
    }

    /**
     * Sets default_prefix
     *
     * @param string $default_prefix Default path prefix for uploads
     *
     * @return self
     */
    public function setDefaultPrefix($default_prefix)
    {
        if (is_null($default_prefix)) {
            throw new \InvalidArgumentException('non-nullable default_prefix cannot be null');
        }
        $this->container['default_prefix'] = $default_prefix;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


