<?php
/**
 * PDFToolsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TemplateFox\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use TemplateFox\ApiException;
use TemplateFox\Configuration;
use TemplateFox\FormDataProcessor;
use TemplateFox\HeaderSelector;
use TemplateFox\ObjectSerializer;

/**
 * PDFToolsApi Class Doc Comment
 *
 * @category Class
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PDFToolsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'extractPdfPages' => [
            'application/json',
        ],
        'mergePdf' => [
            'application/json',
        ],
        'rotatePdf' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation extractPdfPages
     *
     * Extract pages from a PDF
     *
     * @param  \TemplateFox\Model\ExtractPdfPagesRequest $extract_pdf_pages_request extract_pdf_pages_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['extractPdfPages'] to see the possible values for this operation
     *
     * @throws \TemplateFox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \TemplateFox\Model\PdfToolsResponse
     */
    public function extractPdfPages($extract_pdf_pages_request, string $contentType = self::contentTypes['extractPdfPages'][0])
    {
        list($response) = $this->extractPdfPagesWithHttpInfo($extract_pdf_pages_request, $contentType);
        return $response;
    }

    /**
     * Operation extractPdfPagesWithHttpInfo
     *
     * Extract pages from a PDF
     *
     * @param  \TemplateFox\Model\ExtractPdfPagesRequest $extract_pdf_pages_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['extractPdfPages'] to see the possible values for this operation
     *
     * @throws \TemplateFox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \TemplateFox\Model\PdfToolsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function extractPdfPagesWithHttpInfo($extract_pdf_pages_request, string $contentType = self::contentTypes['extractPdfPages'][0])
    {
        $request = $this->extractPdfPagesRequest($extract_pdf_pages_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TemplateFox\Model\PdfToolsResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TemplateFox\Model\PdfToolsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TemplateFox\Model\PdfToolsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation extractPdfPagesAsync
     *
     * Extract pages from a PDF
     *
     * @param  \TemplateFox\Model\ExtractPdfPagesRequest $extract_pdf_pages_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['extractPdfPages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function extractPdfPagesAsync($extract_pdf_pages_request, string $contentType = self::contentTypes['extractPdfPages'][0])
    {
        return $this->extractPdfPagesAsyncWithHttpInfo($extract_pdf_pages_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation extractPdfPagesAsyncWithHttpInfo
     *
     * Extract pages from a PDF
     *
     * @param  \TemplateFox\Model\ExtractPdfPagesRequest $extract_pdf_pages_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['extractPdfPages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function extractPdfPagesAsyncWithHttpInfo($extract_pdf_pages_request, string $contentType = self::contentTypes['extractPdfPages'][0])
    {
        $returnType = '\TemplateFox\Model\PdfToolsResponse';
        $request = $this->extractPdfPagesRequest($extract_pdf_pages_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'extractPdfPages'
     *
     * @param  \TemplateFox\Model\ExtractPdfPagesRequest $extract_pdf_pages_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['extractPdfPages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function extractPdfPagesRequest($extract_pdf_pages_request, string $contentType = self::contentTypes['extractPdfPages'][0])
    {

        // verify the required parameter 'extract_pdf_pages_request' is set
        if ($extract_pdf_pages_request === null || (is_array($extract_pdf_pages_request) && count($extract_pdf_pages_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $extract_pdf_pages_request when calling extractPdfPages'
            );
        }


        $resourcePath = '/v1/pdf-tools/extract-pages';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($extract_pdf_pages_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($extract_pdf_pages_request));
            } else {
                $httpBody = $extract_pdf_pages_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation mergePdf
     *
     * Merge PDFs
     *
     * @param  \TemplateFox\Model\MergePdfRequest $merge_pdf_request merge_pdf_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['mergePdf'] to see the possible values for this operation
     *
     * @throws \TemplateFox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \TemplateFox\Model\PdfToolsResponse
     */
    public function mergePdf($merge_pdf_request, string $contentType = self::contentTypes['mergePdf'][0])
    {
        list($response) = $this->mergePdfWithHttpInfo($merge_pdf_request, $contentType);
        return $response;
    }

    /**
     * Operation mergePdfWithHttpInfo
     *
     * Merge PDFs
     *
     * @param  \TemplateFox\Model\MergePdfRequest $merge_pdf_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['mergePdf'] to see the possible values for this operation
     *
     * @throws \TemplateFox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \TemplateFox\Model\PdfToolsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function mergePdfWithHttpInfo($merge_pdf_request, string $contentType = self::contentTypes['mergePdf'][0])
    {
        $request = $this->mergePdfRequest($merge_pdf_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TemplateFox\Model\PdfToolsResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TemplateFox\Model\PdfToolsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TemplateFox\Model\PdfToolsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation mergePdfAsync
     *
     * Merge PDFs
     *
     * @param  \TemplateFox\Model\MergePdfRequest $merge_pdf_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['mergePdf'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function mergePdfAsync($merge_pdf_request, string $contentType = self::contentTypes['mergePdf'][0])
    {
        return $this->mergePdfAsyncWithHttpInfo($merge_pdf_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation mergePdfAsyncWithHttpInfo
     *
     * Merge PDFs
     *
     * @param  \TemplateFox\Model\MergePdfRequest $merge_pdf_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['mergePdf'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function mergePdfAsyncWithHttpInfo($merge_pdf_request, string $contentType = self::contentTypes['mergePdf'][0])
    {
        $returnType = '\TemplateFox\Model\PdfToolsResponse';
        $request = $this->mergePdfRequest($merge_pdf_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'mergePdf'
     *
     * @param  \TemplateFox\Model\MergePdfRequest $merge_pdf_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['mergePdf'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function mergePdfRequest($merge_pdf_request, string $contentType = self::contentTypes['mergePdf'][0])
    {

        // verify the required parameter 'merge_pdf_request' is set
        if ($merge_pdf_request === null || (is_array($merge_pdf_request) && count($merge_pdf_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $merge_pdf_request when calling mergePdf'
            );
        }


        $resourcePath = '/v1/pdf-tools/merge';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($merge_pdf_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($merge_pdf_request));
            } else {
                $httpBody = $merge_pdf_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation rotatePdf
     *
     * Rotate pages of a PDF
     *
     * @param  \TemplateFox\Model\RotatePdfRequest $rotate_pdf_request rotate_pdf_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rotatePdf'] to see the possible values for this operation
     *
     * @throws \TemplateFox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \TemplateFox\Model\PdfToolsResponse
     */
    public function rotatePdf($rotate_pdf_request, string $contentType = self::contentTypes['rotatePdf'][0])
    {
        list($response) = $this->rotatePdfWithHttpInfo($rotate_pdf_request, $contentType);
        return $response;
    }

    /**
     * Operation rotatePdfWithHttpInfo
     *
     * Rotate pages of a PDF
     *
     * @param  \TemplateFox\Model\RotatePdfRequest $rotate_pdf_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rotatePdf'] to see the possible values for this operation
     *
     * @throws \TemplateFox\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \TemplateFox\Model\PdfToolsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function rotatePdfWithHttpInfo($rotate_pdf_request, string $contentType = self::contentTypes['rotatePdf'][0])
    {
        $request = $this->rotatePdfRequest($rotate_pdf_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TemplateFox\Model\PdfToolsResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TemplateFox\Model\PdfToolsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TemplateFox\Model\PdfToolsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation rotatePdfAsync
     *
     * Rotate pages of a PDF
     *
     * @param  \TemplateFox\Model\RotatePdfRequest $rotate_pdf_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rotatePdf'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function rotatePdfAsync($rotate_pdf_request, string $contentType = self::contentTypes['rotatePdf'][0])
    {
        return $this->rotatePdfAsyncWithHttpInfo($rotate_pdf_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation rotatePdfAsyncWithHttpInfo
     *
     * Rotate pages of a PDF
     *
     * @param  \TemplateFox\Model\RotatePdfRequest $rotate_pdf_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rotatePdf'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function rotatePdfAsyncWithHttpInfo($rotate_pdf_request, string $contentType = self::contentTypes['rotatePdf'][0])
    {
        $returnType = '\TemplateFox\Model\PdfToolsResponse';
        $request = $this->rotatePdfRequest($rotate_pdf_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'rotatePdf'
     *
     * @param  \TemplateFox\Model\RotatePdfRequest $rotate_pdf_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rotatePdf'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function rotatePdfRequest($rotate_pdf_request, string $contentType = self::contentTypes['rotatePdf'][0])
    {

        // verify the required parameter 'rotate_pdf_request' is set
        if ($rotate_pdf_request === null || (is_array($rotate_pdf_request) && count($rotate_pdf_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rotate_pdf_request when calling rotatePdf'
            );
        }


        $resourcePath = '/v1/pdf-tools/rotate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($rotate_pdf_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($rotate_pdf_request));
            } else {
                $httpBody = $rotate_pdf_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
