<?php
/**
 * CreateAsyncPdfRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TemplateFox\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateAsyncPdfRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Request model for async PDF generation
 * @package     TemplateFox
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateAsyncPdfRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateAsyncPdfRequest"
     */
    public function testCreateAsyncPdfRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "template_id"
     */
    public function testPropertyTemplateId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "export_type"
     */
    public function testPropertyExportType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expiration"
     */
    public function testPropertyExpiration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "filename"
     */
    public function testPropertyFilename()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "store_s3"
     */
    public function testPropertyStoreS3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "s3_filepath"
     */
    public function testPropertyS3Filepath()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "s3_bucket"
     */
    public function testPropertyS3Bucket()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "webhook_url"
     */
    public function testPropertyWebhookUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "webhook_secret"
     */
    public function testPropertyWebhookSecret()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
