<?php
/**
 * S3TestResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TemplateFox\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * S3TestResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Response for S3 connection test
 * @package     TemplateFox
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class S3TestResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "S3TestResponse"
     */
    public function testS3TestResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "success"
     */
    public function testPropertySuccess()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
