<?php
/**
 * IntegrationsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace TemplateFox\Test\Api;

use \TemplateFox\Configuration;
use \TemplateFox\ApiException;
use \TemplateFox\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * IntegrationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  TemplateFox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IntegrationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteS3Config
     *
     * Delete S3 configuration.
     *
     */
    public function testDeleteS3Config()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getS3Config
     *
     * Get S3 configuration.
     *
     */
    public function testGetS3Config()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for saveS3Config
     *
     * Save S3 configuration.
     *
     */
    public function testSaveS3Config()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for testS3Connection
     *
     * Test S3 connection.
     *
     */
    public function testTestS3Connection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
